name: .NET 8.0 Build, Publish, and Artifact Upload

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore GateSwitchWay.sln

      - name: Build Solution
        run: dotnet build GateSwitchWay.sln --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish GateSwitchWay.sln --configuration Release -r win-x64 --output publish

      - name: Install dotnet-warp
        run: dotnet tool install --global dotnet-warp

      - name: Get version and build executable
        run: |
          $version = $(git describe --tags --abbrev=0)
          dotnet-warp --input publish --output GateSwitchWay-$version.exe
        
      - name: Upload Published Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-artifacts
          path: GateSwitchWay-*.exe
